//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pizzawoolfEntities : DbContext
    {
        public pizzawoolfEntities()
            : base("name=pizzawoolfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<блюда> блюда { get; set; }
        public DbSet<блюда_в_заказе> блюда_в_заказе { get; set; }
        public DbSet<Заказ> Заказ { get; set; }
        public DbSet<категории> категории { get; set; }
        public DbSet<Клиенты> Клиенты { get; set; }
        public DbSet<сотрудники> сотрудники { get; set; }
    }
}
