//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pizzawoolfEF : DbContext
    {
        public pizzawoolfEF()
            : base("name=pizzawoolfEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<блюда> блюда { get; set; }
        public virtual DbSet<блюда_в_заказе> блюда_в_заказе { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<категории> категории { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<сотрудники> сотрудники { get; set; }
    }
}
