//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class блюда_в_заказе
    {
        public long id_БЗ { get; set; }
        public string кол_во { get; set; }
        public long id_заказа { get; set; }
        public long id_блюда { get; set; }
    
        public virtual блюда блюда { get; set; }
        public virtual Заказ Заказ { get; set; }
    }
}
