//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.блюда_в_заказе = new HashSet<блюда_в_заказе>();
        }
    
        public long id_заказа { get; set; }
        public string сумма { get; set; }
        public long id_клиента { get; set; }
        public Nullable<long> id_сотрудника { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<блюда_в_заказе> блюда_в_заказе { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual сотрудники сотрудники { get; set; }
    }
}
